// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AddLocale struct {
	UserID    int64      `json:"userID"`
	ProjectID int64      `json:"projectID"`
	Locale    *Newlocale `json:"locale"`
}

type AddProject struct {
	UserID      int64        `json:"userID"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Locales     []*Newlocale `json:"locales"`
}

type AuthInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type AuthResponse struct {
	AuthToken *AuthToken `json:"authToken"`
	User      *User      `json:"user"`
}

type AuthToken struct {
	AccessToken string    `json:"accessToken"`
	ExpiredAt   time.Time `json:"expiredAt"`
}

type CustomMutationResolver struct {
	CreateLocale *Locale `json:"createLocale"`
}

type DeleteProject struct {
	ID int64 `json:"id"`
}

type Locale struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Code string `json:"code"`
}

type LocaleOps struct {
	UpdateLocale *Locale `json:"updateLocale"`
	DeleteLocale bool    `json:"deleteLocale"`
}

type Mutation struct {
}

type Newlocale struct {
	LangName    string `json:"langName"`
	LangCode    string `json:"langCode"`
	CountryName string `json:"countryName"`
	CountryCode string `json:"countryCode"`
}

type Project struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Locales     []*Locale `json:"locales"`
}

type Query struct {
}

type RegisterInput struct {
	FirstName       string `json:"firstName"`
	LastName        string `json:"lastName"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
}

type UpdateProject struct {
	ID          int64   `json:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}
