// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddLocale struct {
	UserID      string `json:"userID"`
	ProjectID   string `json:"projectID"`
	LangName    string `json:"langName"`
	LangCode    string `json:"langCode"`
	CountryName string `json:"countryName"`
	CountryCode string `json:"countryCode"`
}

type AddProject struct {
	UserID      string `json:"userID"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type AddUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Locale struct {
	ID   *string `json:"id,omitempty"`
	Name string  `json:"name"`
	Code string  `json:"code"`
}

type Mutation struct {
}

type Project struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Locales     []*Locale `json:"locales"`
}

type Query struct {
}

type User struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Email    string     `json:"email"`
	Projects []*Project `json:"projects"`
}
