DROP TABLE IF EXISTS "media";
DROP TABLE IF EXISTS "value_version";
DROP TABLE IF EXISTS "api_keys";
DROP TABLE IF EXISTS "project_user";
DROP TABLE IF EXISTS "comment";
DROP TABLE IF EXISTS "value";
DROP TABLE IF EXISTS "key";
DROP TABLE IF EXISTS "locale";
DROP TABLE IF EXISTS "upload";
DROP TABLE IF EXISTS "backup";
DROP TABLE IF EXISTS "project";
DROP TABLE IF EXISTS "user";


DROP TYPE IF EXISTS key_type;
DROP TYPE IF EXISTS value_status;